added echo of error and exit if failed

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -73,4 +73,6 @@ jobs:
                 echo "Command executed Successfully"
               else 
                 echo "Command failed"
+                echo "Error: "$status"
+                exit 1
               fi
